### ISSUE TITLE
DV2102 Homey Link not working

### ISSUE THREAD

**Issue by Manthazar** [jghaanstra/com.doorbird#19]
The device is not reachable after pairing (red alert sign)

What happened before:
1. Add device 
2. Select Doorbird. The next window is not finding any device.
3. Select 'manual pairing '. Enter ip, user, password
4. Test connection --> ok!
5. Click Add
6. Device gets added, but is marked as not reachable.

**Comment by jghaanstra** [comment]
Could you send me a crash report from the app settings.

**Comment by Manthazar** [comment]
Hi,thanks for your prompt reply. This should it be: a68bcf74-171c-44ab-83fc-845934ceb0d6Cheers,Aron
-------- Ursprüngliche Nachricht --------Von: Jelger Haanstra <notifications@github.com> Datum: 09.03.21  07:24  (GMT+01:00) An: "jghaanstra/com.doorbird" <com.doorbird@noreply.github.com> Cc: Manthazar <arko@denobrium.de>, Author <author@noreply.github.com> Betreff: Re: [jghaanstra/com.doorbird] DV2102 Homey Link not working (#19) 
Could you send me a crash report from the app settings.

**Comment by jghaanstra** [comment]
The error indicates you are using a username/ password combination that is not authorized to use the API. Make sure the credentials are correct and the user has the correct permissions as described in the instructions on the support forum.

```
---- stderr ----
2021-03-04 12:54:37 [err] [ManagerDrivers] [doorbird] [0] Device.onInit Error: Error: Error 401: this user is not authorized, make sure you have created the user in the app and entered the correct details.
    at checkStatus (/lib/util.js:300:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-04 13:55:25 [err] [ManagerDrivers] [doorbird] [0] Device.onInit Error: Error: Error 401: this user is not authorized, make sure you have created the user in the app and entered the correct details.
    at checkStatus (/lib/util.js:300:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
